force-app-gwb-source-code/Salesforce_GWB-main/force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Auth Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app-gwb-source-code/Salesforce_GWB-main/force-app/main/default/objects/Plant_Collaborator__c/Plant_Collaborator__c.object-meta.xml
<CustomObject>
    <description>PR1064302-225 : Object to store Plant backup admins for each plant
PR1064302-468 : Updated Name as Plant Collaborator</description>
    <label>Plant Collaborator</label>
    <nameField>
        <displayFormat>PBA-{0000}</displayFormat>
        <label>Plant Backup Admin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plant Collaborators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-gwb-source-code/Salesforce_GWB-main/force-app/main/default/objects/Plant_Collaborator__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <label>Access Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Collaborator_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Read only</fullName>
            </value>
            <value>
                <fullName>Read/Edit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-gwb-source-code/Salesforce_GWB-main/force-app/main/default/objects/Plant_Collaborator__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipName>Plant_Backup_Admins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app-gwb-source-code/Salesforce_GWB-main/force-app/main/default/objects/Plant_Collaborator__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plant_Collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-gwb-source-code/Salesforce_GWB-main/force-app/main/default/classes/PlantCollaboratorTriggerHandler.cls
/**
 * @description Handler class for Plant_Collaborator__c trigger.
 */
public class PlantCollaboratorTriggerHandler {
    /**
     * @description Main handler method for Plant_Collaborator__c deletion.
     * @param oldRecords List of deleted Plant_Collaborator__c records
     */
    public static void handleAfterDelete(List<Plant_Collaborator__c> oldRecords) {
        if (oldRecords.isEmpty()) return;
        
        Set<Id> plantIds = new Set<Id>();
        
        for (Plant_Collaborator__c pc : oldRecords) {
            if (pc.Plant__c != null) {
                plantIds.add(pc.Plant__c);
            }
        }
        
        Map<Id, Plant__c> plantMap = new Map<Id, Plant__c>(
            [
                SELECT Id, Name
                FROM Plant__c
                WHERE Id IN :plantIds
            ]
        );
        
        Set<String> groupNames = new Set<String>();
        Set<Id> userIds = new Set<Id>();
        
        Map<String, String> userToGroupNameMap = new Map<String, String>();
        
        for (Plant_Collaborator__c pc : oldRecords) {
            Plant__c plantRec = plantMap.get(pc.Plant__c);
            
            if (pc.User__c == null || plantRec == null || String.isBlank(plantRec.Name)) continue;
            
            String formattedPlantName = plantRec.Name.replace(' ', '_');

            String groupName;
            
            if (pc.Access_Level__c == 'Read Only') {
                groupName = formattedPlantName + '_R';
            }
            else if (pc.Access_Level__c == 'Read/Edit') {
                groupName = formattedPlantName + '_RW';
            }
            
            if (String.isNotBlank(groupName)) {
                groupNames.add(groupName);
                userIds.add(pc.User__c);
                
                userToGroupNameMap.put(
                    pc.User__c,
                    groupName
                );
            }
        }
        
        if (groupNames.isEmpty() || userIds.isEmpty()) return;
        
        Map<String, Id> groupNameToIdMap = new Map<String, Id>();

        for (Group grp : [
            SELECT Id, Name
            FROM Group
            WHERE Type = 'Regular'
            AND Name IN :groupNames
        ]) {
            
            groupNameToIdMap.put(grp.Name,grp.Id);
        }
        
        if (groupNameToIdMap.isEmpty()) return;
        
        List<GroupMember> existingMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember
                                             WHERE UserOrGroupId IN :userIds AND GroupId IN :groupNameToIdMap.values()];
        
        Set<Id> groupMemberIdsToDelete = new Set<Id>();
        
        for (GroupMember gm : existingMembers) {

            String expectedGroupName = userToGroupNameMap.get((Id)gm.UserOrGroupId);

            Id expectedGroupId = groupNameToIdMap.get(expectedGroupName);

            if (gm.GroupId == expectedGroupId) {
                groupMemberIdsToDelete.add(gm.Id);
            }
        }
        
        /*
         * Queueable Call
         */
        if (!groupMemberIdsToDelete.isEmpty()) {

            System.enqueueJob(
                new PlantCollaboratorGroupRemovalQueueable(
                    new List<Id>(groupMemberIdsToDelete)
                )
            );
        }
    }

}